/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingLayoutRouteImport } from './routes/onboarding/_layout'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as OnboardingLayoutStep5RouteImport } from './routes/onboarding/_layout/step5'
import { Route as OnboardingLayoutStep4RouteImport } from './routes/onboarding/_layout/step4'
import { Route as OnboardingLayoutStep3RouteImport } from './routes/onboarding/_layout/step3'
import { Route as OnboardingLayoutStep2RouteImport } from './routes/onboarding/_layout/step2'
import { Route as AuthLayoutLoginRouteImport } from './routes/auth/_layout/login'
import { Route as AuthLayoutCreateRouteImport } from './routes/auth/_layout/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLayoutRoute = OnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const OnboardingLayoutStep5Route = OnboardingLayoutStep5RouteImport.update({
  id: '/step5',
  path: '/step5',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const OnboardingLayoutStep4Route = OnboardingLayoutStep4RouteImport.update({
  id: '/step4',
  path: '/step4',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const OnboardingLayoutStep3Route = OnboardingLayoutStep3RouteImport.update({
  id: '/step3',
  path: '/step3',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const OnboardingLayoutStep2Route = OnboardingLayoutStep2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutCreateRoute = AuthLayoutCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/create': typeof AuthLayoutCreateRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/onboarding/step2': typeof OnboardingLayoutStep2Route
  '/onboarding/step3': typeof OnboardingLayoutStep3Route
  '/onboarding/step4': typeof OnboardingLayoutStep4Route
  '/onboarding/step5': typeof OnboardingLayoutStep5Route
  '/dashboard/': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/create': typeof AuthLayoutCreateRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/onboarding/step2': typeof OnboardingLayoutStep2Route
  '/onboarding/step3': typeof OnboardingLayoutStep3Route
  '/onboarding/step4': typeof OnboardingLayoutStep4Route
  '/onboarding/step5': typeof OnboardingLayoutStep5Route
  '/dashboard': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/onboarding/_layout': typeof OnboardingLayoutRouteWithChildren
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/_layout/create': typeof AuthLayoutCreateRoute
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
  '/onboarding/_layout/step2': typeof OnboardingLayoutStep2Route
  '/onboarding/_layout/step3': typeof OnboardingLayoutStep3Route
  '/onboarding/_layout/step4': typeof OnboardingLayoutStep4Route
  '/onboarding/_layout/step5': typeof OnboardingLayoutStep5Route
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/onboarding/'
    | '/api/auth/$'
    | '/auth/create'
    | '/auth/login'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/api/auth/$'
    | '/auth/create'
    | '/auth/login'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth/_layout'
    | '/dashboard/_layout'
    | '/onboarding/_layout'
    | '/onboarding/'
    | '/api/auth/$'
    | '/auth/_layout/create'
    | '/auth/_layout/login'
    | '/onboarding/_layout/step2'
    | '/onboarding/_layout/step3'
    | '/onboarding/_layout/step4'
    | '/onboarding/_layout/step5'
    | '/dashboard/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/_layout': {
      id: '/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/onboarding/_layout/step5': {
      id: '/onboarding/_layout/step5'
      path: '/step5'
      fullPath: '/onboarding/step5'
      preLoaderRoute: typeof OnboardingLayoutStep5RouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/step4': {
      id: '/onboarding/_layout/step4'
      path: '/step4'
      fullPath: '/onboarding/step4'
      preLoaderRoute: typeof OnboardingLayoutStep4RouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/step3': {
      id: '/onboarding/_layout/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof OnboardingLayoutStep3RouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/step2': {
      id: '/onboarding/_layout/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof OnboardingLayoutStep2RouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/create': {
      id: '/auth/_layout/create'
      path: '/create'
      fullPath: '/auth/create'
      preLoaderRoute: typeof AuthLayoutCreateRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutCreateRoute: typeof AuthLayoutCreateRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutCreateRoute: AuthLayoutCreateRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface OnboardingLayoutRouteChildren {
  OnboardingLayoutStep2Route: typeof OnboardingLayoutStep2Route
  OnboardingLayoutStep3Route: typeof OnboardingLayoutStep3Route
  OnboardingLayoutStep4Route: typeof OnboardingLayoutStep4Route
  OnboardingLayoutStep5Route: typeof OnboardingLayoutStep5Route
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingLayoutStep2Route: OnboardingLayoutStep2Route,
  OnboardingLayoutStep3Route: OnboardingLayoutStep3Route,
  OnboardingLayoutStep4Route: OnboardingLayoutStep4Route,
  OnboardingLayoutStep5Route: OnboardingLayoutStep5Route,
}

const OnboardingLayoutRouteWithChildren =
  OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
